:aws_account_id: 
:access_key_id: 
:secret_access_key: 
:billing_bucket: 
:staging_bucket: 
:production_bucket:
:staging_prefix: 
:keyname: 
:region:
:publishing_role_arn: 
:reports_dir: reports
:includes_file: staging_files_manifest
:ignores_file: .gitignore
:cloudfront_distribution: :mappings_filename: mappings.amzn-linux.2013.3.json
